export enum EntityTypes {
    USER = 'user',
    PROFILE = 'profile',
    UPLOAD = 'upload',
    MODULES = 'module',
    ROUTES = 'route',
    ROLE = 'role',
    FUNCTION = 'function',
    API = 'api',
    METHOD = 'method',
    ACCOUNT_TYPE = 'account_type',
    GAME = 'game',
    RANK = 'rank',
    GAME_HISTORY = 'game_history',
}
